#!/usr/bin/env python3
from sys import argv

from scripts.namer import namer_main


if __name__ == '__main__':
    if len(argv) <= 1:
        print("Need to supply script name and then arguments to pass to that "
              "script!")
        exit()
    if argv[1] == 'namer':
        namer_main()
    else:
        print("I'm not fully functional yet, I don't know how to run the "
              "script {}".format(argv[1]))




